Write the response body of a request to the output

diff --git a/bin/qtools-test.in b/bin/qtools-test.in
--- a/bin/qtools-test.in
+++ b/bin/qtools-test.in
@@ -41,6 +41,11 @@ fi
 echo "qtools-test: Send and receive PASSED"
 
 qrespond --verbose $url --max 1 &
-qrequest --verbose $url -r abc
+response_message=$(qrequest --verbose $url -r abc)
+
+if [[ $response_message != ABC ]]; then
+    echo "qtools-test: Request and respond FAILED"
+    exit 1
+fi
 
 echo "qtools-test: Request and respond PASSED"
